version: '3.3'

services:      
  addresslookup-gateway-api:
    build:
      context: ./
      dockerfile: AddressLookUp.Aggregator.Api/Dockerfile
    ports:
     - "5085:80"
     
  ping-api:
    build:
      context: ./
      dockerfile: PingWorker.Api/Dockerfile
    ports:
     - "5700:80"
     
  geoip-api:
    build:
      context: ./
      dockerfile: GeoIpWorker.Api/Dockerfile
    ports:
     - "5701:80"
     
  rdap-api:
    build:
      context: ./
      dockerfile: RdapWorker.Api/Dockerfile
    ports:
     - "5702:80"
     
  reversedns-api:
    build:
      context: ./
      dockerfile: ReverseDnsWorker.Api/Dockerfile
    ports:
     - "5703:80"
     
  domain-availability-api:
    build:
      context: ./
      dockerfile: DomainAvailabilityWorker.Api/Dockerfile
    ports:
     - "5704:80"